### ISSUE TITLE
Extraction may not work correctly if the backing data is also modified during the transformation

### ISSUE THREAD

**Issue by andy-fong** [solo-io/envoy-gloo#367]
Example config that could trigger this issue:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: dev-gw
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - foo.com
    routes:
    - matchers:
      - regex: /ab/c.*
      options:
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                logRequestResponseInfo: true
                transformationTemplate:
                  advancedTemplates: true
                  extractors:
                    mypath:
                      header: ':path'
                      regex: ^\/ab\/c\/([^/]+)(.*)$
                      subgroup: 1
                    mypath2:
                      header: ':path'
                      regex: ^\/ab\/c\/([^/]+)(.*)$
                      subgroup: 2
                  headers:
                    host-header:
                      text: '{{ extraction("mypath") }}'
                    :path:
                      text: '{{ extraction("mypath2") }}'
        timeout: 31s
      routeAction:
        dynamicForwardProxy:
          autoHostRewriteHeader: "host-header"
```

Explanation:
Here we are trying to extract part of the path and put that into header but also remove that part in the path. The extraction in this mode is stored in a string_veiw that requires the backing data (in this case, the `:path` header string) to be unchanged. 

Workaround:
coming soon
